env:
  es6: true
  browser: true
  node: true
parserOptions:
  ecmaVersion: 2020 # Node.js v14+
  sourceType: module # Enable ES6 style import
  allowImportExportEverywhere": true # Enable ES6 style import
plugins:
  - import
extends:
  - "@lightyears1998/lightyears-style"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
